"""
05_train_short_term_forecaster.py

Paper 3 short-term workload forecasting.

Models:
    1. HGB
    2. CP-HGB

Paper 3 design reproduced:
    - Complete five-minute interval series
    - Chronological partitions:
          Train       : intervals 0 -> 12,383
          Calibration: intervals 12,384 -> 14,975
          Test        : intervals 14,976 -> 17,565
    - Causal lagged features
    - Causal shifted rolling features
    - log1p target
    - HGB
    - CP-HGB
    - No random split
    - No test-set training

Important:
    The first 288 observations do not have enough historical
    information for the maximum lag/rolling history.

    These rows are NOT filled.

    They are excluded from the modeled training sample,
    while the original chronological partition boundaries
    remain unchanged.

Input:
    data/workload_features_5min.csv

Outputs:
    models/workload_forecaster/paper3_hgb.joblib
    models/workload_forecaster/paper3_cp_hgb.joblib

    results/predictions/workload_forecast_predictions.csv

    results/validation/workload_forecaster_metadata.json
"""


from pathlib import Path
import json

import joblib
import numpy as np
import pandas as pd

from sklearn.ensemble import HistGradientBoostingRegressor


# ============================================================
# PROJECT PATHS
# ============================================================

ROOT = Path(__file__).resolve().parents[1]

INPUT_FILE = ROOT / "data" / "workload_features_5min.csv"

MODEL_DIR = ROOT / "models" / "workload_forecaster"

PREDICTION_DIR = ROOT / "results" / "predictions"

VALIDATION_DIR = ROOT / "results" / "validation"


MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

PREDICTION_DIR.mkdir(
    parents=True,
    exist_ok=True
)

VALIDATION_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# CONSTANTS
# ============================================================

SEED = 42

TARGET_COLUMN = "target_next_5min"

INTERVAL_COLUMN = "interval"


# ============================================================
# PAPER 3 EXACT CHRONOLOGICAL PARTITIONS
# ============================================================

TRAIN_START = 0
TRAIN_END = 12383

CALIBRATION_START = 12384
CALIBRATION_END = 14975

TEST_START = 14976
TEST_END = 17565


# Maximum history required by Paper 3:
#
# lag 288
#
# Therefore intervals 0 -> 287 cannot have a complete
# 288-bin lag/rolling history.

MAX_HISTORY = 288


# ============================================================
# PAPER 3 FEATURE DEFINITIONS
# ============================================================

LAGS = [
    1,
    2,
    3,
    6,
    12,
    24,
    72,
    144,
    288,
]

ROLLING_WINDOWS = [
    3,
    12,
    72,
    288,
]

ROLLING_MAX_WINDOWS = [
    12,
    72,
    288,
]

CALENDAR_FEATURES = [
    "daily_sin",
    "daily_cos",
    "weekly_sin",
    "weekly_cos",
]

CP_FEATURES = [
    "cp_change_score",
    "cp_change_alarm",
    "cp_short_long_ratio",
    "cp_elapsed_bins",
]


# ============================================================
# COLUMN RESOLUTION
# ============================================================

def resolve_column(
    columns,
    candidates,
    description
):
    """
    Resolve the actual column generated by Module 04.

    Module 04 is treated as the source of truth for the
    physical column names.
    """

    for candidate in candidates:

        if candidate in columns:
            return candidate

    raise ValueError(
        "\nCould not resolve required feature:\n"
        f"  {description}\n\n"
        "Checked:\n"
        +
        "\n".join(
            f"  - {candidate}"
            for candidate in candidates
        )
    )


# ============================================================
# RESOLVE MODULE 04 FEATURES
# ============================================================

def resolve_workload_features(df):

    columns = set(df.columns)

    resolved = {}

    # --------------------------------------------------------
    # LAGS
    # --------------------------------------------------------

    for lag in LAGS:

        resolved[
            f"lag_{lag}"
        ] = resolve_column(
            columns,
            [
                f"lag_{lag}",
                f"total_tokens_lag_{lag}",
                f"total_tokens_lag{lag}",
                f"token_lag_{lag}",
            ],
            f"lag {lag}",
        )

    # --------------------------------------------------------
    # ROLLING MEAN
    # --------------------------------------------------------

    for window in ROLLING_WINDOWS:

        resolved[
            f"rolling_mean_{window}"
        ] = resolve_column(
            columns,
            [
                f"rolling_mean_{window}",
                f"total_tokens_rolling_mean_{window}",
                f"rolling_mean_{window}_tokens",
            ],
            f"rolling mean {window}",
        )

    # --------------------------------------------------------
    # ROLLING STD
    # --------------------------------------------------------

    for window in ROLLING_WINDOWS:

        resolved[
            f"rolling_std_{window}"
        ] = resolve_column(
            columns,
            [
                f"rolling_std_{window}",
                f"total_tokens_rolling_std_{window}",
                f"rolling_std_{window}_tokens",
            ],
            f"rolling standard deviation {window}",
        )

    # --------------------------------------------------------
    # ROLLING MAX
    # --------------------------------------------------------

    for window in ROLLING_MAX_WINDOWS:

        resolved[
            f"rolling_max_{window}"
        ] = resolve_column(
            columns,
            [
                f"rolling_max_{window}",
                f"total_tokens_rolling_max_{window}",
                f"rolling_max_{window}_tokens",
            ],
            f"rolling maximum {window}",
        )

    # --------------------------------------------------------
    # CALENDAR
    # --------------------------------------------------------

    for feature in CALENDAR_FEATURES:

        resolved[feature] = resolve_column(
            columns,
            [
                feature
            ],
            feature
        )

    # --------------------------------------------------------
    # CHANGE-POINT FEATURES
    # --------------------------------------------------------

    for feature in CP_FEATURES:

        resolved[feature] = resolve_column(
            columns,
            [
                feature
            ],
            feature
        )

    return resolved


# ============================================================
# BUILD FEATURE LISTS
# ============================================================

def build_feature_lists(resolved):

    hgb_features = []

    # 9 lag features

    for lag in LAGS:

        hgb_features.append(
            resolved[
                f"lag_{lag}"
            ]
        )

    # 4 rolling means

    for window in ROLLING_WINDOWS:

        hgb_features.append(
            resolved[
                f"rolling_mean_{window}"
            ]
        )

    # 4 rolling standard deviations

    for window in ROLLING_WINDOWS:

        hgb_features.append(
            resolved[
                f"rolling_std_{window}"
            ]
        )

    # 3 rolling maxima

    for window in ROLLING_MAX_WINDOWS:

        hgb_features.append(
            resolved[
                f"rolling_max_{window}"
            ]
        )

    # 4 calendar features

    for feature in CALENDAR_FEATURES:

        hgb_features.append(
            resolved[feature]
        )

    # CP-HGB additions

    cp_features = []

    for feature in CP_FEATURES:

        cp_features.append(
            resolved[feature]
        )

    cp_hgb_features = (
        hgb_features
        +
        cp_features
    )

    return (
        hgb_features,
        cp_hgb_features,
        cp_features
    )


# ============================================================
# VALIDATE FEATURE DEFINITIONS
# ============================================================

def validate_feature_definitions(
    hgb_features,
    cp_hgb_features
):

    if len(hgb_features) != 24:

        raise RuntimeError(
            "Expected 24 HGB features, "
            f"found {len(hgb_features)}."
        )

    if len(cp_hgb_features) != 28:

        raise RuntimeError(
            "Expected 28 CP-HGB features, "
            f"found {len(cp_hgb_features)}."
        )

    if len(set(hgb_features)) != 24:

        raise RuntimeError(
            "Duplicate HGB feature columns detected."
        )

    if len(set(cp_hgb_features)) != 28:

        raise RuntimeError(
            "Duplicate CP-HGB feature columns detected."
        )

    print(
        "Feature definition validation: PASS"
    )


# ============================================================
# CHECK FUTURE TARGET
# ============================================================

def check_future_target(df):

    print(
        "\n[3] Checking future target availability..."
    )

    missing = int(
        df[TARGET_COLUMN]
        .isna()
        .sum()
    )

    print(
        f"Rows with missing future target: "
        f"{missing}"
    )

    if missing != 1:

        raise ValueError(
            "Expected exactly one final row "
            "without a future target."
        )

    print(
        "Final row has no t+1 target."
    )

    print(
        "It will be excluded from supervised "
        "model fitting."
    )

    return df


# ============================================================
# TARGET VALIDATION
# ============================================================

def validate_target(df):

    print(
        "\n[4] Validating target..."
    )

    usable_target = df[
        TARGET_COLUMN
    ].dropna()

    values = usable_target.to_numpy()

    if not np.isfinite(values).all():

        raise ValueError(
            "Target contains non-finite values."
        )

    if (values < 0).any():

        raise ValueError(
            "Target contains negative values."
        )

    print(
        f"Usable target rows: "
        f"{len(values):,}"
    )

    print(
        f"Target minimum: "
        f"{values.min():,.2f}"
    )

    print(
        f"Target maximum: "
        f"{values.max():,.2f}"
    )

    print(
        "Target validation: PASS"
    )


# ============================================================
# FEATURE VALIDATION
# ============================================================

def validate_feature_matrix(
    df,
    features,
    model_name
):

    print(
        f"\nValidating {model_name} feature matrix..."
    )

    missing = [
        feature
        for feature in features
        if feature not in df.columns
    ]

    if missing:

        print(
            "\nMissing features:"
        )

        for feature in missing:

            print(
                f"  {feature}"
            )

        raise ValueError(
            f"{model_name} is missing "
            "required features."
        )

    values = df[
        features
    ]

    nan_count = int(
        values.isna()
        .sum()
        .sum()
    )

    print(
        f"Expected features : "
        f"{len(features)}"
    )

    print(
        f"Actual features   : "
        f"{len(features)}"
    )

    print(
        f"Feature NaNs      : "
        f"{nan_count}"
    )

    return nan_count


# ============================================================
# CREATE EXACT PAPER 3 PARTITIONS
# ============================================================

def create_paper3_partitions(df):

    print(
        "\n[6] Creating Paper 3 chronological partitions..."
    )

    # --------------------------------------------------------
    # IMPORTANT:
    #
    # We preserve the original interval boundaries.
    #
    # We DO NOT create a new proportional split after
    # removing warm-up observations.
    # --------------------------------------------------------

    train = df[
        (
            df[INTERVAL_COLUMN]
            >= TRAIN_START
        )
        &
        (
            df[INTERVAL_COLUMN]
            <= TRAIN_END
        )
    ].copy()

    calibration = df[
        (
            df[INTERVAL_COLUMN]
            >= CALIBRATION_START
        )
        &
        (
            df[INTERVAL_COLUMN]
            <= CALIBRATION_END
        )
    ].copy()

    test = df[
        (
            df[INTERVAL_COLUMN]
            >= TEST_START
        )
        &
        (
            df[INTERVAL_COLUMN]
            <= TEST_END
        )
    ].copy()

    print(
        "\nOriginal chronological partitions:"
    )

    print(
        f"Training       : "
        f"{len(train):,}"
    )

    print(
        f"Calibration    : "
        f"{len(calibration):,}"
    )

    print(
        f"Locked test    : "
        f"{len(test):,}"
    )

    return (
        train,
        calibration,
        test
    )


# ============================================================
# REMOVE TRAINING WARM-UP ONLY
# ============================================================

def remove_training_warmup(
    train,
    hgb_features,
    cp_hgb_features
):

    print(
        "\n[7] Removing unavailable training history..."
    )

    # Paper 3 requires up to lag 288.
    #
    # Therefore the first 288 interval positions cannot
    # contain a complete feature history.
    #
    # We remove those rows from the MODELLED training set.
    #
    # We do NOT alter the actual partition boundary.

    before = len(train)

    # Rows with complete HGB feature history

    hgb_valid = (
        ~train[
            hgb_features
        ].isna().any(axis=1)
    )

    cp_valid = (
        ~train[
            cp_hgb_features
        ].isna().any(axis=1)
    )

    valid = (
        hgb_valid
        &
        cp_valid
    )

    train_modelled = train[
        valid
    ].copy()

    train_modelled.reset_index(
        drop=True,
        inplace=True
    )

    removed = (
        before
        -
        len(train_modelled)
    )

    print(
        f"Training rows before warm-up : "
        f"{before:,}"
    )

    print(
        f"Training rows removed         : "
        f"{removed:,}"
    )

    print(
        f"Training rows modelled        : "
        f"{len(train_modelled):,}"
    )

    print(
        f"First modelled training interval: "
        f"{train_modelled[INTERVAL_COLUMN].iloc[0]}"
    )

    return train_modelled


# ============================================================
# VALIDATE CALIBRATION AND TEST FEATURES
# ============================================================

def validate_later_partitions(
    calibration,
    test,
    features,
):

    calibration_nan = int(
        calibration[
            features
        ]
        .isna()
        .sum()
        .sum()
    )

    test_nan = int(
        test[
            features
        ]
        .isna()
        .sum()
        .sum()
    )

    print(
        f"Calibration feature NaNs: "
        f"{calibration_nan}"
    )

    print(
        f"Test feature NaNs       : "
        f"{test_nan}"
    )

    if calibration_nan != 0:

        raise ValueError(
            "Calibration partition contains "
            "unexpected feature NaNs."
        )

    if test_nan != 0:

        raise ValueError(
            "Test partition contains "
            "unexpected feature NaNs."
        )


# ============================================================
# VALIDATE CHRONOLOGY
# ============================================================

def validate_chronology(
    train,
    calibration,
    test
):

    print(
        "\n[8] Checking chronological ordering..."
    )

    train_start = int(
        train[
            INTERVAL_COLUMN
        ].iloc[0]
    )

    train_end = int(
        train[
            INTERVAL_COLUMN
        ].iloc[-1]
    )

    calibration_start = int(
        calibration[
            INTERVAL_COLUMN
        ].iloc[0]
    )

    calibration_end = int(
        calibration[
            INTERVAL_COLUMN
        ].iloc[-1]
    )

    test_start = int(
        test[
            INTERVAL_COLUMN
        ].iloc[0]
    )

    test_end = int(
        test[
            INTERVAL_COLUMN
        ].iloc[-1]
    )

    print(
        f"Modelled training : "
        f"{train_start} -> {train_end}"
    )

    print(
        f"Calibration       : "
        f"{calibration_start} -> "
        f"{calibration_end}"
    )

    print(
        f"Locked test       : "
        f"{test_start} -> {test_end}"
    )

    if not (
        train_end < calibration_start
        and
        calibration_end < test_start
    ):

        raise RuntimeError(
            "Chronological ordering failed."
        )

    print(
        "Chronological ordering: PASS"
    )


# ============================================================
# TRAIN MODEL
# ============================================================

def train_model(
    X_train,
    y_train,
    model_name
):

    print(
        f"\nTraining {model_name}..."
    )

    model = HistGradientBoostingRegressor(

        max_iter=80,

        learning_rate=0.07,

        max_leaf_nodes=31,

        min_samples_leaf=30,

        l2_regularization=1.0,

        random_state=SEED,
    )

    model.fit(
        X_train,
        y_train
    )

    print(
        f"{model_name} training complete."
    )

    return model


# ============================================================
# PREDICTION
# ============================================================

def generate_predictions(
    model,
    X
):

    log_predictions = model.predict(
        X
    )

    predictions = np.expm1(
        log_predictions
    )

    predictions = np.clip(
        predictions,
        0,
        None
    )

    return predictions


# ============================================================
# VALIDATE PREDICTIONS
# ============================================================

def validate_predictions(
    predictions,
    name
):

    if not np.isfinite(
        predictions
    ).all():

        raise RuntimeError(
            f"{name} contains non-finite "
            "predictions."
        )

    if (
        predictions < 0
    ).any():

        raise RuntimeError(
            f"{name} contains negative "
            "predictions."
        )

    print(
        f"{name:<25}"
        f"min={predictions.min():,.2f} "
        f"max={predictions.max():,.2f}"
    )


# ============================================================
# SAVE PREDICTIONS
# ============================================================

def save_predictions(
    train,
    calibration,
    test,

    hgb_train,
    hgb_calibration,
    hgb_test,

    cp_train,
    cp_calibration,
    cp_test
):

    train_output = pd.DataFrame({

        "interval":
            train[
                INTERVAL_COLUMN
            ].to_numpy(),

        "split":
            "train",

        "actual_next_5min_tokens":
            train[
                TARGET_COLUMN
            ].to_numpy(),

        "hgb_prediction":
            hgb_train,

        "cp_hgb_prediction":
            cp_train,
    })

    calibration_output = pd.DataFrame({

        "interval":
            calibration[
                INTERVAL_COLUMN
            ].to_numpy(),

        "split":
            "calibration",

        "actual_next_5min_tokens":
            calibration[
                TARGET_COLUMN
            ].to_numpy(),

        "hgb_prediction":
            hgb_calibration,

        "cp_hgb_prediction":
            cp_calibration,
    })

    test_output = pd.DataFrame({

        "interval":
            test[
                INTERVAL_COLUMN
            ].to_numpy(),

        "split":
            "test",

        "actual_next_5min_tokens":
            test[
                TARGET_COLUMN
            ].to_numpy(),

        "hgb_prediction":
            hgb_test,

        "cp_hgb_prediction":
            cp_test,
    })

    output = pd.concat(
        [
            train_output,
            calibration_output,
            test_output
        ],
        ignore_index=True
    )

    output_file = (
        PREDICTION_DIR
        /
        "workload_forecast_predictions.csv"
    )

    output.to_csv(
        output_file,
        index=False
    )

    print(
        "\nPredictions saved:"
    )

    print(
        f"  {output_file}"
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print(
        "=" * 70
    )

    print(
        "PAPER 3 SHORT-TERM WORKLOAD FORECASTING"
    )

    print(
        "=" * 70
    )

    # ========================================================
    # 1. LOAD
    # ========================================================

    print(
        "\n[1] Loading workload feature matrix..."
    )

    if not INPUT_FILE.exists():

        raise FileNotFoundError(
            f"\nInput file not found:\n"
            f"{INPUT_FILE}"
        )

    df = pd.read_csv(
        INPUT_FILE
    )

    print(
        f"Rows loaded: {len(df):,}"
    )

    print(
        f"Columns: {len(df.columns)}"
    )

    # ========================================================
    # 2. RESOLVE FEATURES
    # ========================================================

    print(
        "\n[2] Resolving Paper 3 features "
        "from Module 04 output..."
    )

    resolved = resolve_workload_features(
        df
    )

    (
        hgb_features,
        cp_hgb_features,
        cp_features
    ) = build_feature_lists(
        resolved
    )

    print(
        f"HGB predictors    : "
        f"{len(hgb_features)}"
    )

    print(
        f"CP-HGB predictors : "
        f"{len(cp_hgb_features)}"
    )

    validate_feature_definitions(
        hgb_features,
        cp_hgb_features
    )

    # ========================================================
    # 3. FUTURE TARGET
    # ========================================================

    check_future_target(
        df
    )

    # ========================================================
    # 4. TARGET VALIDATION
    # ========================================================

    validate_target(
        df
    )

    # ========================================================
    # 5. FEATURE VALIDATION
    # ========================================================

    print(
        "\n[5] Checking feature history..."
    )

    hgb_nan_count = (
        validate_feature_matrix(
            df,
            hgb_features,
            "HGB"
        )
    )

    cp_hgb_nan_count = (
        validate_feature_matrix(
            df,
            cp_hgb_features,
            "CP-HGB"
        )
    )

    print(
        "\nThe initial feature NaNs are expected:"
    )

    print(
        "They represent unavailable historical "
        "information, not missing observations "
        "that should be imputed."
    )

    # ========================================================
    # 6. EXACT PAPER 3 SPLITS
    # ========================================================

    (
        train_full,
        calibration,
        test
    ) = create_paper3_partitions(
        df
    )

    # ========================================================
    # 7. REMOVE ONLY TRAINING WARM-UP
    # ========================================================

    train = remove_training_warmup(
        train_full,
        hgb_features,
        cp_hgb_features
    )

    # Later partitions should have complete history

    validate_later_partitions(
        calibration,
        test,
        cp_hgb_features
    )

    # ========================================================
    # 8. CHRONOLOGY
    # ========================================================

    validate_chronology(
        train,
        calibration,
        test
    )

    # ========================================================
    # TARGET AVAILABILITY
    # ========================================================

    if train[
        TARGET_COLUMN
    ].isna().any():

        raise RuntimeError(
            "Training contains missing targets."
        )

    if calibration[
        TARGET_COLUMN
    ].isna().any():

        raise RuntimeError(
            "Calibration contains missing targets."
        )

    # The final interval 17,565 has no next target.
    #
    # It belongs to the observed test interval range, but
    # cannot be scored as a one-step-ahead supervised example.
    #
    # Therefore exclude only that final row from test modeling
    # and prediction output.

    test_modelled = test[
        test[
            TARGET_COLUMN
        ].notna()
    ].copy()

    test_modelled.reset_index(
        drop=True,
        inplace=True
    )

    print(
        "\nTest rows with usable future targets: "
        f"{len(test_modelled):,}"
    )

    print(
        "Final observed interval without t+1 "
        "target is excluded from supervised scoring."
    )

    # ========================================================
    # 9. PREPARE TARGET
    # ========================================================

    print(
        "\n[9] Applying log1p target transformation..."
    )

    y_train_raw = train[
        TARGET_COLUMN
    ].to_numpy()

    y_calibration_raw = calibration[
        TARGET_COLUMN
    ].to_numpy()

    y_test_raw = test_modelled[
        TARGET_COLUMN
    ].to_numpy()

    y_train = np.log1p(
        y_train_raw
    )

    print(
        f"Training target rows: "
        f"{len(y_train):,}"
    )

    print(
        "Transformation: log1p"
    )

    print(
        "Target preparation: PASS"
    )

    # ========================================================
    # 10. FEATURE MATRICES
    # ========================================================

    print(
        "\n[10] Preparing model matrices..."
    )

    X_train_hgb = train[
        hgb_features
    ]

    X_calibration_hgb = calibration[
        hgb_features
    ]

    X_test_hgb = test_modelled[
        hgb_features
    ]

    X_train_cp = train[
        cp_hgb_features
    ]

    X_calibration_cp = calibration[
        cp_hgb_features
    ]

    X_test_cp = test_modelled[
        cp_hgb_features
    ]

    # Final NaN check on actual modelling matrices

    if X_train_hgb.isna().any().any():
        raise RuntimeError(
            "HGB training matrix still contains NaNs."
        )

    if X_train_cp.isna().any().any():
        raise RuntimeError(
            "CP-HGB training matrix still contains NaNs."
        )

    if X_calibration_hgb.isna().any().any():
        raise RuntimeError(
            "HGB calibration matrix contains NaNs."
        )

    if X_test_hgb.isna().any().any():
        raise RuntimeError(
            "HGB test matrix contains NaNs."
        )

    if X_calibration_cp.isna().any().any():
        raise RuntimeError(
            "CP-HGB calibration matrix contains NaNs."
        )

    if X_test_cp.isna().any().any():
        raise RuntimeError(
            "CP-HGB test matrix contains NaNs."
        )

    print(
        "Final modelling matrices: PASS"
    )

    # ========================================================
    # 11. TRAIN HGB
    # ========================================================

    hgb_model = train_model(
        X_train_hgb,
        y_train,
        "HGB"
    )

    # ========================================================
    # 12. TRAIN CP-HGB
    # ========================================================

    cp_hgb_model = train_model(
        X_train_cp,
        y_train,
        "CP-HGB"
    )

    # ========================================================
    # 13. PREDICTIONS
    # ========================================================

    print(
        "\n[13] Generating predictions..."
    )

    hgb_train = generate_predictions(
        hgb_model,
        X_train_hgb
    )

    hgb_calibration = generate_predictions(
        hgb_model,
        X_calibration_hgb
    )

    hgb_test = generate_predictions(
        hgb_model,
        X_test_hgb
    )

    cp_train = generate_predictions(
        cp_hgb_model,
        X_train_cp
    )

    cp_calibration = generate_predictions(
        cp_hgb_model,
        X_calibration_cp
    )

    cp_test = generate_predictions(
        cp_hgb_model,
        X_test_cp
    )

    # ========================================================
    # 14. PREDICTION VALIDATION
    # ========================================================

    print(
        "\n[14] Validating predictions..."
    )

    validate_predictions(
        hgb_train,
        "HGB train"
    )

    validate_predictions(
        hgb_calibration,
        "HGB calibration"
    )

    validate_predictions(
        hgb_test,
        "HGB test"
    )

    validate_predictions(
        cp_train,
        "CP-HGB train"
    )

    validate_predictions(
        cp_calibration,
        "CP-HGB calibration"
    )

    validate_predictions(
        cp_test,
        "CP-HGB test"
    )

    print(
        "Prediction validation: PASS"
    )

    # ========================================================
    # 15. SAVE MODELS
    # ========================================================

    print(
        "\n[15] Saving models..."
    )

    hgb_model_file = (
        MODEL_DIR
        /
        "paper3_hgb.joblib"
    )

    cp_hgb_model_file = (
        MODEL_DIR
        /
        "paper3_cp_hgb.joblib"
    )

    joblib.dump(
        hgb_model,
        hgb_model_file
    )

    joblib.dump(
        cp_hgb_model,
        cp_hgb_model_file
    )

    print(
        f"HGB model:\n  {hgb_model_file}"
    )

    print(
        f"CP-HGB model:\n  {cp_hgb_model_file}"
    )

    # ========================================================
    # 16. SAVE PREDICTIONS
    # ========================================================

    print(
        "\n[16] Saving predictions..."
    )

    save_predictions(
        train,
        calibration,
        test_modelled,

        hgb_train,
        hgb_calibration,
        hgb_test,

        cp_train,
        cp_calibration,
        cp_test
    )

    # ========================================================
    # 17. SAVE METADATA
    # ========================================================

    print(
        "\n[17] Saving experiment metadata..."
    )

    metadata = {

        "module":
            "05_train_short_term_forecaster",

        "method":
            "Paper 3 HGB and CP-HGB",

        "input_file":
            str(INPUT_FILE),

        "dataset":
            "BurstGPT_1",

        "original_intervals":
            17566,

        "original_interval_range":
            [
                0,
                17565
            ],

        "paper3_partitions": {

            "training": {
                "start": TRAIN_START,
                "end": TRAIN_END,
                "intervals": 12384
            },

            "calibration": {
                "start": CALIBRATION_START,
                "end": CALIBRATION_END,
                "intervals": 2592
            },

            "test": {
                "start": TEST_START,
                "end": TEST_END,
                "intervals": 2590
            }
        },

        "modelled_training_rows":
            len(train),

        "modelled_calibration_rows":
            len(calibration),

        "modelled_test_rows":
            len(test_modelled),

        "training_warmup_rows_removed":
            len(train_full) - len(train),

        "final_test_row_without_future_target":
            True,

        "target":
            TARGET_COLUMN,

        "target_transformation":
            "log1p",

        "inverse_prediction_transformation":
            "expm1",

        "maximum_history":
            MAX_HISTORY,

        "hgb_feature_count":
            len(hgb_features),

        "cp_hgb_feature_count":
            len(cp_hgb_features),

        "hgb_features":
            hgb_features,

        "cp_hgb_additional_features":
            cp_features,

        "resolved_columns":
            resolved,

        "hyperparameters": {

            "max_iter":
                80,

            "learning_rate":
                0.07,

            "max_leaf_nodes":
                31,

            "min_samples_leaf":
                30,

            "l2_regularization":
                1.0,

            "random_state":
                SEED
        },

        "training_method":
            "chronological",

        "random_split":
            False,

        "test_used_for_training":
            False,

        "test_used_for_feature_engineering":
            False,

        "forecast_metrics_calculated":
            False,

        "uncertainty_calibration":
            False
    }

    metadata_file = (
        VALIDATION_DIR
        /
        "workload_forecaster_metadata.json"
    )

    with open(
        metadata_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            metadata,
            file,
            indent=2
        )

    print(
        f"Metadata saved:\n  {metadata_file}"
    )

    # ========================================================
    # FINAL
    # ========================================================

    print(
        "\n"
        + "-" * 70
    )

    print(
        "PAPER 3 WORKLOAD FORECASTING COMPLETE"
    )

    print(
        "-" * 70
    )

    print(
        "\nCreated:"
    )

    print(
        "  models/workload_forecaster/"
        "paper3_hgb.joblib"
    )

    print(
        "  models/workload_forecaster/"
        "paper3_cp_hgb.joblib"
    )

    print(
        "  results/predictions/"
        "workload_forecast_predictions.csv"
    )

    print(
        "  results/validation/"
        "workload_forecaster_metadata.json"
    )

    print(
        "\nImportant:"
    )

    print(
        "  Paper 3 chronological boundaries preserved."
    )

    print(
        "  Warm-up feature rows were NOT imputed."
    )

    print(
        "  Test data was NOT used for training."
    )

    print(
        "  Forecast metrics were NOT calculated yet."
    )

    print(
        "  No model was declared better."
    )

    print(
        "\n"
        + "=" * 70
    )

    print(
        "05 COMPLETE"
    )

    print(
        "=" * 70
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()